name: Arconomy
version: ${project.version}
main: fr.weefle.Arconomy
authors: [Weefle]
description: Plugin d'économie officiel pour le réseau Arcania
commands:
  arconomy:
    description: Commande principale d'Arconomy
    usage: /arconomy
